package main

import agents.User;
import agents.Taxi;

global org.apache.log4j.Logger gLogger;
global Integer DISTANCE_BETWEEN_REVISIONS;

rule "send taxies to revisions"
    when
        $taxi: Taxi(getDistanceTraveled() > DISTANCE_BETWEEN_REVISIONS,
        			getCurrentStatus() == Taxi.Status.AVAILABLE)
    then
        gLogger.info("MainRules::Sending to revision taxi " + $taxi + " with distance traveled " + $taxi.getDistanceTraveled());
		$taxi.goToRevision();
end

rule "send revized taxies back to work"
	when 
		$taxi: Taxi(getCurrentStatus() == Taxi.Status.IN_REVISION,
					isRevisionComplete() == true)
	then 
		gLogger.info("MainRules::Sending back to work taxi " + $taxi);
		$taxi.resetDistanceTraveled();
		$taxi.goToWork();
end